export const FETCH_CATEGORIES = "FETCH_CATEGORIES";

export const FETCH_POSTS = "FETCH_POSTS";
export const ADD_POST = "ADD_POST";
export const FETCH_POST = "FETCH_POST";
export const UPDATE_POST = "UPDATE_POST";
export const REMOVE_POST = "REMOVE_POST";

export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENT_BY_POST_ID = "FETCH_COMMENT_BY_POST_ID";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
